### ISSUE TITLE
Groups won't work because of API change

### ISSUE THREAD

**Issue by amirc** [eladnava/facebook-alerts#3]
Hey, great project!
I think Facebook has changed the API and now this project won't work for groups.
It could save some people time to change the readme.

**Comment by eladnava** [comment]
Hi @amirc,
Thanks so much for the positive feedback!

You are correct, in Facebook API 2.3 and up, you can no longer query for group posts. However, this is already clearly mentioned in the README:

```
Facebook Groups (requires Facebook app with v2.3 Graph API version support)
```

Is it possible you may have missed this?

**Comment by amirc** [comment]
sorry. I did missed that
